apiVersion: v1
kind: Service
metadata:
  name: clbusiintegrationinterfaceweb-svc
  namespace: common
spec:
  ports:
    - name: http
      nodePort: 30008
      port: 13949
      protocol: TCP
      targetPort: 13949
  selector:
    app: clbusiintegrationinterfaceweb
  sessionAffinity: None
  type: NodePort
