apiVersion: apps/v1
kind: Deployment
metadata:
  name: clbusiintegrationinterfaceweb
  namespace: common
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clbusiintegrationinterfaceweb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clbusiintegrationinterfaceweb
    spec:
      containers:
        - env:
            - name: MYENV_TOMCATPORT
            {{- if not .Values.clbusiintegrationinterfaceweb.networkManager.tomcat.port }}
              value: {{ .Values.clbusiintegrationinterfaceweb.networkManager.tomcat.port | quote }}
            {{- else }}
              value: '13949'
            {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.clbusiintegrationinterfaceweb.resourceManager.jvm }}
          {{- if not .Values.commonConfig.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clbusiintegrationinterfaceweb:{{ .Values.clbusiintegrationinterfaceweb.nodeManager.tag }}
          {{- else }}
          image: {{ .Values.imageRegistry }}/clbusiintegrationinterfaceweb:{{ .Values.dockerTag }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              {{- if not .Values.clbusiintegrationinterfaceweb.networkManager.tomcat.port }}
              port: {{ .Values.clbusiintegrationinterfaceweb.networkManager.tomcat.port }}
              {{- else }}
              port: 13949
              {{- end }}
            timeoutSeconds: 10
          name: clbusiintegrationinterfaceweb
          ports:
            {{- if not .Values.clbusiintegrationinterfaceweb.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clbusiintegrationinterfaceweb.networkManager.tomcat.port}}
              hostPort: {{ .Values.clbusiintegrationinterfaceweb.networkManager.tomcat.port}}
              protocol: TCP
            {{- else }}
            - containerPort: 13949
              hostPort: 13949
              protocol: TCP
            {{- end }}
            {{- if not .Values.clbusiintegrationinterfaceweb.networkManager.thrift.port }}
            - containerPort: {{ .Values.clbusiintegrationinterfaceweb.networkManager.thrift.port }}
              hostPort: {{ .Values.clbusiintegrationinterfaceweb.networkManager.thrift.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 13951
              hostPort: 13951
              protocol: TCP
            {{- end }}
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              {{- if not .Values.clbusiintegrationinterfaceweb.networkManager.tomcat.port }}
              port: {{ .Values.clbusiintegrationinterfaceweb.networkManager.tomcat.port }}
              {{- else }}
              port: 13949
              {{- end }}
            timeoutSeconds: 10
          {{- if .Values.clbusiintegrationinterfaceweb.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clbusiintegrationinterfaceweb.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clbusiintegrationinterfaceweb.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clbusiintegrationinterfaceweb.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clbusiintegrationinterfaceweb.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
            - mountPath: /home/nacfg.ini
              name: nacfg
            - mountPath: /usr/local/soft/tomcat/webapps/ROOT/WEB-INF/config
              name: config
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env: common
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
    {{- if not .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - hostPath:
            path: {{ .Values.hostManager.volumes.nacfgPath }}/nacfg.ini
            type: ''
          name: nacfg
        - configMap:
            defaultMode: 420
            name: clbusiintegrationinterfaceweb-config
          name: config
    {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
        - configMap:
            defaultMode: 420
            name: clbusiintegrationinterfaceweb-config
          name: config
    {{- end }}
