apiVersion: v1
kind: Service
metadata:
  name: clbusshotelh5-svc
  namespace: jd
spec:
  ports:
    - name: http
      nodePort: 30618
      port: 30618
      protocol: TCP
      targetPort: 18189
  selector:
    app: clbusshotelh5
  sessionAffinity: None
  type: NodePort
