apiVersion: v1
data:
  DBRoute.properties: |-
    driver=com.mysql.jdbc.Driver
    readurl={{ .Values.configMapManger.db.databaserouteR.url }}
    readusername={{ .Values.configMapManger.db.databaserouteR.username }}
    readpassword={{ .Values.configMapManger.db.databaserouteR.username }}
    writeurl={{ .Values.configMapManger.db.databaserouteW.url }}
    writeusername={{ .Values.configMapManger.db.databaserouteW.username }}
    writepassword={{ .Values.configMapManger.db.databaserouteW.username }}
  ServiceRoute.properties: |-
    uniqueSign=Jav-CLYPG-192
    ########## JDBC ##########################
    driver=com.mysql.jdbc.Driver
    url={{ .Values.configMapManger.db.serviceroute.url }}
    username={{ .Values.configMapManger.db.serviceroute.username }}
    password={{ .Values.configMapManger.db.serviceroute.password }}
    ###########cxf timeOut###########################
    cxf.connectionTimeout = 5000000
    cxf.readtimeout = 5000000
  jdbc.properties: |-
    applicationName = CLCityLineSetDBServiceZS
    databaseName = CLCityLineSetting
    isRead = true
    bizTime = 2014-12-19
    dataSourceTimeout=3600
    showSql=true
    pool.initialSize=10
    pool.maxActive=100
    pool.maxIdle=10
    pool.maxWait=10
    showResult=true
    pool.poolPreparedStatements=true
    pool.defaultAutoCommit=true
    routeTimeout= 0
    keyIdConfigPath=/home/nacfg.ini
    thrift.port=12662
    console=true
    isCallHotelDataService=true
  log4j.properties: >-
    ### 把日志信息输出到控制台 ###

    log4j.appender.stdout=org.apache.log4j.ConsoleAppender

    #log4j.appender.stdout.Target=System.err

    #log4j.appender.stdout=org.apache.log4j

    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout


    ### 把日志信息输出到文件：jbit.log ###

    #log4j.appender.logfile=org.apache.log4j.FileAppender

    log4j.appender.logfile=org.apache.log4j.DailyRollingFileAppender

    log4j.appender.logfile.DatePattern='_'yyyy-MM-dd'.log'

    log4j.appender.logfile.File=${catalina.home}/webapps/517Log/CLAirTicketRuleDataServiceCS.log

    log4j.appender.logfile.layout=org.apache.log4j.PatternLayout

    log4j.appender.logfile.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %F
    %p %m%n


    ###显示SQL语句部分 正式环境注释以下部分

    log4j.logger.com.ibatis=DEBUG 

    log4j.logger.com.ibatis.common.jdbc.SimpleDataSource=DEBUG 

    log4j.logger.com.ibatis.common.jdbc.ScriptRunner=DEBUG 

    log4j.logger.com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate=DEBUG 

    log4j.logger.java.sql.Connection=DEBUG 

    log4j.logger.java.sql.Statement=DEBUG 

    log4j.logger.java.sql.PreparedStatement=DEBUG
  log_config.properties: >-
    log.AppName = CLCityLineSetDBServiceZS


    #AppRecord App日志记录开关 true：开     false：关

    log.AppRecord = true


    #DebugRecord Debug日志记录开关 true：开     false：关

    log.DebugRecord = false


    #Driver 数据库驱动

    log.jdbc.driver = com.mysql.jdbc.Driver


    #Url 数据库链接  jdbc:mysql://ip：port/数据库名称

    log.acc.jdbc.url = jdbc:mysql://172.17.51.252:3306/InterLogAcc

    log.acc.jdbc.username=vxSs4i7BS58@

    log.acc.jdbc.password=6BPzhGiVwAPCW1LhtdUvCblGokvcMGesrY1wV/coEWg@


    log.app.jdbc.url = jdbc:mysql://172.17.51.252:3306/InterLogApp

    log.app.jdbc.username=vxSs4i7BS58@

    log.app.jdbc.password=6BPzhGiVwAPCW1LhtdUvCblGokvcMGesrY1wV/coEWg@


    log.cachehit.jdbc.url = jdbc:mysql://172.17.51.252:3306/InterLogCacheHit

    log.cachehit.jdbc.username=vxSs4i7BS58@

    log.cachehit.jdbc.password=6BPzhGiVwAPCW1LhtdUvCblGokvcMGesrY1wV/coEWg@


    log.debug.jdbc.url = jdbc:mysql://172.17.51.252:3306/InterLogDebug

    log.debug.jdbc.username=vxSs4i7BS58@

    log.debug.jdbc.password=6BPzhGiVwAPCW1LhtdUvCblGokvcMGesrY1wV/coEWg@


    log.exception.jdbc.url = jdbc:mysql://172.17.51.252:3306/InterLogException

    log.exception.jdbc.username=vxSs4i7BS58@

    log.exception.jdbc.password=6BPzhGiVwAPCW1LhtdUvCblGokvcMGesrY1wV/coEWg@


    log.interaction.jdbc.url =
    jdbc:mysql://172.17.51.252:3306/InterLogInteraction

    log.interaction.jdbc.username=vxSs4i7BS58@

    log.interaction.jdbc.password=6BPzhGiVwAPCW1LhtdUvCblGokvcMGesrY1wV/coEWg@


    log.slowcall.jdbc.url = jdbc:mysql://172.17.51.252:3306/InterLogSlowCall

    log.slowcall.jdbc.username=vxSs4i7BS58@

    log.slowcall.jdbc.password=6BPzhGiVwAPCW1LhtdUvCblGokvcMGesrY1wV/coEWg@


    log.uiacc.jdbc.url = jdbc:mysql://172.17.51.252:3306/InterLogUiacc

    log.uiacc.jdbc.username=vxSs4i7BS58@

    log.uiacc.jdbc.password=6BPzhGiVwAPCW1LhtdUvCblGokvcMGesrY1wV/coEWg@


    #Directory linux下日志记录路径?

    log.Directory = /var/log/cllog

    #DivisionFileSize （单位：兆） 日志在某一时间段内超过文件大小已2M划分

    log.DivisionFileSize = 2

    #DivisionFileTime （单位：分钟） 日志在某一时间段内不足2M文件按2min划分

    log.DivisionFileTime = 1

    #windows下载文件目录,windows服务的配置成Logs，linux服务一般配置成 JavaLogs

    log.download.Directory=JavaLogs

    log.kafka.iswritetokafka=1

    log.kafka.addresses=kafkalog1.517la.com:9092,kafkalog2.517la.com:9092,kafkalog3.517la.com:9092
  param-jdbc.properties: |-
    ########## JDBC ##########################
    param.applicationName = CLCityLineSetDBService
    param.databaseName = SysParamDB
    param.isRead = true
    param.bizTime = 2014-12-19
    param.showSql=true

    # \u5b57\u5178\u7f13\u5b58\u8d85\u65f6\u65f6\u95f4
    param.DictionaryTimeOut=2
    #\u7edf\u4e00\u53c2\u6570\u7f13\u5b58\u8d85\u65f6\u65f6\u95f4
    param.SysParamTimeOut=2
    #\u90e8\u5206\u53c2\u6570\u7f13\u5b58\u8d85\u65f6\u65f6\u95f4
    param.UserParamTimeOut=2
kind: ConfigMap
metadata:
  name: clcitylinesetdbservice-config
  namespace: common
