apiVersion: v1
kind: Service
metadata:
  name: clcitylinesetdbservice-svc
  namespace: common
spec:
  ports:
    - name: thrift
      port: 12662
      protocol: TCP
      targetPort: 12662
  selector:
    app: clcitylinesetdbservice
  sessionAffinity: None
  type: ClusterIP
