apiVersion: v1
kind: Service
metadata:
  name: clintegrationinterfaceservice-svc
  namespace: common
spec:
  ports:
    - name: http
      nodePort: 30009
      port: 12233
      protocol: TCP
      targetPort: 12233
  selector:
    app: clintegrationinterfaceservice
  sessionAffinity: None
  type: NodePort
