apiVersion: apps/v1
kind: Deployment
metadata:
  name: cltradeintegrateservice
  namespace: common
spec:
  progressDeadlineSeconds: 600
  {{- if not .Values.commonConfig.nodeManager.replicas }}
  replicas: {{ .Values.commonConfig.nodeManager.replicas }}
  {{- else if eq .Values.environment "test" }}
  replicas: 1
  {{- else if eq .Values.antiAffinity "formal" }}
  replicas: 2
  {{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cltradeintegrateservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cltradeintegrateservice
    spec:
      containers:
        - env:
            - name: MYENV_TOMCATPORT
              value: '15666'
            - name: JAVA_OPTS
              value: {{ .Values.cltradeintegrateservice.resourceManager.jvm }}
          {{- if not .Values.commonConfig.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/cltradeintegrateservice:{{ .Values.cltradeintegrateservice.nodeManager.tag }}
          {{- else }}
          image: {{ .Values.imageRegistry }}/cltradeintegrateservice:{{ .Values.dockerTag }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          name: cltradeintegrateservice
          ports:
            - containerPort: 15666
              hostPort: 15666
              protocol: TCP
            - containerPort: 15664
              hostPort: 15664
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
            - mountPath: /home/nacfg.ini
              name: nacfg
            - mountPath: /usr/local/soft/tomcat/webapps/ROOT/WEB-INF/config
              name: config
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env: common
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
      {{- if not .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - hostPath:
            path: {{ .Values.hostManager.volumes.nacfgPath }}/nacfg.ini
            type: ''
          name: nacfg
        - configMap:
            defaultMode: 420
            name: cltradeintegrateservice-config
          name: config
      {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
        - configMap:
            defaultMode: 420
            name: cltradeintegrateservice-config
          name: config
      {{- end }}
