apiVersion: v1
kind: Service
metadata:
  name: hotelplatweb-svc
  namespace: jd
spec:
  ports:
    - name: http
      nodePort: 30602
      port: 14037
      protocol: TCP
      targetPort: 14037
  selector:
    app: hotelplatweb
  sessionAffinity: None
  type: NodePort
