apiVersion: v1
kind: Service
metadata:
  name: hotelsellinterfacewebnodeport-svc
  namespace: jd
spec:
  ports:
    - name: http
      nodePort: 30610
      port: 30610
      protocol: TCP
      targetPort: 9624
  selector:
    app: hotelsellinterfaceweb
  sessionAffinity: None
  type: NodePort
