apiVersion: v1
kind: Service
metadata:
  name: hotelpriceruledataservice-svc
  namespace: jd
spec:
  ports:
    - name: http
      nodePort: 30620
      port: 30620
      protocol: TCP
      targetPort: 5239
  selector:
    app: hotelpriceruledataservice
  sessionAffinity: None
  type: NodePort
