#集群方式
apiVersion: v1
kind: Service
metadata:
  name: hotelorderdataservicecloud-svc
  namespace: jd
spec:
  ports:
    - name: http
      port: 14222
      protocol: TCP
      targetPort: 14222
  selector:
    app: hotelorderdataservicecloud
  sessionAffinity: None
  type: ClusterIP
