apiVersion: v1
kind: Service
metadata:
  name: hotelgeographydataservice-svc
  namespace: jd
spec:
  ports:
    - name: http
      nodePort: 30626
      port: 30626
      protocol: TCP
      targetPort: 5217
  selector:
    app: hotelgeographydataservice
  sessionAffinity: None
  type: NodePort
