apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotelplatweb
  namespace: jd
spec:
  progressDeadlineSeconds: 600
  {{- if not .Values.commonConfig.nodeManager.replicas }}
  replicas: {{ .Values.commonConfig.nodeManager.replicas }}
  {{- else if eq .Values.environment "test" }}
  replicas: 1
  {{- else if eq .Values.antiAffinity "formal" }}
  replicas: 2
  {{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hotelplatweb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        redeploy-timestamp: '1600532375996'
      labels:
        app: hotelplatweb
    spec:
      containers:
        - env:
            - name: MYENV_TOMCATPORT
              value: '14037'
            - name: JAVA_OPTS
              value: {{ .Values.hotelplatweb.resourceManager.jvm }}
          {{- if not .Values.commonConfig.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/hotelplatweb:{{ .Values.hotelplatweb.nodeManager.tag }}
          {{- else }}
          image: {{ .Values.imageRegistry }}/hotelplatweb:{{ .Values.dockerTag }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          name: hotelplatweb
          ports:
            - containerPort: 14037
              hostPort: 14037
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
            - mountPath: /home/nacfg.ini
              name: nacfg
            - mountPath: /usr/local/soft/tomcat/webapps/ROOT/WEB-INF/config
              name: config
            - mountPath: /usr/local/soft/tomcat/conf/catalina.properties
              name: config
              subPath: catalina.properties
            - mountPath: /usr/local/soft/tomcat/conf/server.xml
              name: config
              subPath: server.xml
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env: jd
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
      {{- if not .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - hostPath:
            path: {{ .Values.hostManager.volumes.nacfgPath }}/nacfg.ini
            type: ''
          name: nacfg
        - configMap:
            defaultMode: 420
            name: hotelplatweb-config
          name: config
      {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
        - configMap:
            defaultMode: 420
            name: hotelplatweb-config
          name: config
      {{- end }}