apiVersion: v1
kind: Service
metadata:
  name: hotelpurchaseinterfaceweb-svc
  namespace: jd
spec:
  ports:
    - name: thrift
      port: 14315
      protocol: TCP
      targetPort: 14315
  selector:
    app: hotelpurchaseinterfaceweb
  sessionAffinity: None
  type: ClusterIP
