apiVersion: v1
kind: Service
metadata:
  name: hoteltradeintegrateservicecloud-svc
  namespace: jd
spec:
  ports:
    - name: http
      nodePort: 30625
      port: 30625
      protocol: TCP
      targetPort: 14566
  selector:
    app: hoteltradeintegrateservicecloud
  sessionAffinity: None
  type: NodePort
