apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: eureka
  namespace: base
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: eureka
  template:
    metadata:
      labels:
        name: eureka
    spec:
      containers:
        - image: {{ .Values.imageRegistry }}/eureka517la:{{ .Values.eureka.nodeManager.tag }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: eureka
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10
          {{- if .Values.eureka.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.eureka.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.eureka.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.eureka.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.eureka.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 256Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/local/soft/app/application.yml
              name: application
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env: base
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
      volumes:
        - hostPath:
            path: /app/programfiles/eurekafiles/application.yml
            type: ''
          name: application
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
