apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: springcloudconfig
  namespace: base
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: springcloudconfig
  template:
    metadata:
      labels:
        name: springcloudconfig
    spec:
      containers:
        - image: >-
            {{ .Values.imageRegistry }}/springcloudconfigserver517la:{{ .Values.eureka.nodeManager.tag }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
              port: 8094
              scheme: HTTP
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: springcloudconfig
          ports:
            - containerPort: 8094
              hostPort: 8094
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
              port: 8094
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10
          {{- if .Values.springcloudconfig.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.springcloudconfig.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.springcloudconfig.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.springcloudconfig.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.springcloudconfig.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 256Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/local/soft/app/application.yml
              name: application
              subPath: application.yml
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env: base
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: application.yml
                path: application.yml
            name: springcloudconfig
          name: application
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
