apiVersion: apps/v1
kind: Deployment
metadata:
  name: clbussinfodbservice
  namespace: user
spec:
  progressDeadlineSeconds: 600
{{- if .Values.clbussinfodbservice.nodeManager.replicas }}
  replicas: {{ .Values.clbussinfodbservice.nodeManager.replicas }}
{{- else if eq .Values.environment "test" }}
  replicas: 1
{{- else if eq .Values.environment "formal" }}
  replicas: 2
{{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clbussinfodbservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        armsPilotAutoEnable: "on"
        armsPilotCreateAppName: clbussinfodbservice
      creationTimestamp: null
      labels:
        app: clbussinfodbservice
    spec:
      containers:
        - env:
            - name: MYENV_CONFIGNAME
              value: dbroute,jdbc,logconfig,paramjdbc,serviceroute,redis,mqhelper,application,myconfig,systemparam
            - name: MYENV_CONFIGPROFILE
              value: zs
            - name: MYENV_CONFIGLABEL
              value: CLBussInfoDBService-k8s
            - name: MYENV_CONFIGSERVICEID
              value: spring-cloud-config-server
            - name: MYENV_EUREKAURL
              value: http://eureka1:8000/eureka/,http://eureka2:8000/eureka/,http://eureka3:8000/eureka/
            - name: MYENV_TOMCATPORT
            {{- if .Values.clbussinfodbservice.networkManager.tomcat.port }}
              value: {{ .Values.clbussinfodbservice.networkManager.tomcat.port | quote }}
            {{- else }}
              value: "13154"
            {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.clbussinfodbservice.resourceManager.jvm }}
        {{- if .Values.clbussinfodbservice.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clbussinfodbservice:{{ .Values.clbussinfodbservice.nodeManager.tag }}
        {{- else }}
          image: {{ .Values.imageRegistry }}/clbussinfodbservice:{{ .Values.dockerTag }}
        {{- end }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
              {{- if .Values.clbussinfodbservice.networkManager.command.url }}
                command:
                  - curl
                  - {{ .Values.clbussinfodbservice.networkManager.command.url }}
              {{- else }}
                command:
                  - curl
                  - 'http://localhost:13154/unregisterbyext'
              {{- end }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
            {{- if .Values.clbussinfodbservice.networkManager.tomcat.port }}
              port: {{ .Values.clbussinfodbservice.networkManager.tomcat.port }}
            {{- else }}
              port: 13154
            {{- end }}
              scheme: HTTP
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: clbussinfodbservice
          ports:
          {{- if .Values.clbussinfodbservice.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clbussinfodbservice.networkManager.tomcat.port }}
              hostPort: {{ .Values.clbussinfodbservice.networkManager.tomcat.port }}
              protocol: TCP
          {{- else }}
            - containerPort: 13154
              hostPort: 13154
              protocol: TCP
          {{- end }}
          {{- if .Values.clbussinfodbservice.networkManager.thrift.port }}
            - containerPort: {{ .Values.clbussinfodbservice.networkManager.thrift.port }}
              hostPort: {{ .Values.clbussinfodbservice.networkManager.thrift.port }}
              protocol: TCP
          {{- else }}
            - containerPort: 13156
              hostPort: 13156
              protocol: TCP
          {{- end }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
          {{- if .Values.clbussinfodbservice.networkManager.tomcat.port }}
              port: {{ .Values.clbussinfodbservice.networkManager.tomcat.port }}
          {{- else }}
              port: 13154
          {{- end }}
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10
        {{- if .Values.clbussinfodbservice.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clbussinfodbservice.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clbussinfodbservice.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clbussinfodbservice.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clbussinfodbservice.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 128Mi
        {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /srv/access/hz.dat
              name: base
              subPath: hz.dat
            - mountPath: /var/log/java
              name: logjava
            - mountPath: /home/nacfg.ini
              name: base
              subPath: nacfg.ini
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env2: user
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
    {{- if .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            name: base-config
          name: base
    {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            name: base-config
          name: base
    {{- end }}
