apiVersion: v1
kind: Service
metadata:
  name: clbussinfodbservice-nodeport
  namespace: user
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 31016
      port: 13154
      protocol: TCP
      targetPort: 13154
    - name: thrift
      nodePort: 31026
      port: 13156
      protocol: TCP
      targetPort: 13156
  selector:
    app: clbussinfodbservice
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}