apiVersion: v1
kind: Service
metadata:
  name: clbussinfoadminservice-nodeport
  namespace: user
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 31015
      port: 12132
      protocol: TCP
      targetPort: 12132
    - name: thrift
      nodePort: 31025
      port: 12134
      protocol: TCP
      targetPort: 12134
  selector:
    app: clbussinfoadminservice
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
