apiVersion: apps/v1
kind: Deployment
metadata:
  name: clcpysynxxljobexecutor
  namespace: user
spec:
  progressDeadlineSeconds: 600
{{- if .Values.clcpysynxxljobexecutor.nodeManager.replicas }}
  replicas: {{ .Values.clcpysynxxljobexecutor.nodeManager.replicas }}
{{- else if eq .Values.environment "test" }}
  replicas: 1
{{- else if eq .Values.environment "formal" }}
  replicas: 2
{{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clcpysynxxljobexecutor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clcpysynxxljobexecutor
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - cn-beijing-h
                      - cn-beijing-g
      containers:
        - env:
            - name: MYENV_CONFIGNAME
              value: >-
                application,dbroute,logconfig,jdbc,log4j,mqhelper,paramjdbc,redis,serviceroute
            - name: MYENV_CONFIGPROFILE
              value: zs
            - name: MYENV_CONFIGLABEL
              value: CLCpySynXxlJobExecutor-k8s
            - name: MYENV_CONFIGSERVICEID
              value: spring-cloud-config-server
            - name: MYENV_EUREKAURL
              value: >-
                http://eureka1:8000/eureka/,http://eureka2:8000/eureka/,http://eureka3:8000/eureka/
            - name: MYENV_TOMCATPORT
            {{- if .Values.clcpysynxxljobexecutor.networkManager.tomcat.port }}
              value: {{ .Values.clcpysynxxljobexecutor.networkManager.tomcat.port | quote }}
            {{- else }}
              value: "15236"
            {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.clcpysynxxljobexecutor.resourceManager.jvm }}
        {{- if .Values.clcpysynxxljobexecutor.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clcpysynxxljobexecutor:{{ .Values.clcpysynxxljobexecutor.nodeManager.tag }}
        {{- else }}
          image: {{ .Values.imageRegistry }}/clcpysynxxljobexecutor:{{ .Values.dockerTag }}
        {{- end }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
              {{- if .Values.clcpysynxxljobexecutor.networkManager.command.url }}
                command:
                  - curl
                  - {{ .Values.clcpysynxxljobexecutor.networkManager.command.url }}
              {{- else }}
                command:
                  - curl
                  - 'http://localhost:15236/unregisterbyext'
              {{- end }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
            {{- if .Values.clcpysynxxljobexecutor.networkManager.tomcat.port }}
              port: {{ .Values.clcpysynxxljobexecutor.networkManager.tomcat.port }}
            {{- else }}
              port: 15236
            {{- end }}
              scheme: HTTP
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: clcpysynxxljobexecutor
          ports:
        {{- if .Values.clcpysynxxljobexecutor.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clcpysynxxljobexecutor.networkManager.tomcat.port }}
              hostPort: {{ .Values.clcpysynxxljobexecutor.networkManager.tomcat.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 15236
              hostPort: 15236
              protocol: TCP
            {{- end }}
            {{- if .Values.clcpysynxxljobexecutor.networkManager.thrift.port }}
            - containerPort: {{ .Values.clcpysynxxljobexecutor.networkManager.thrift.port }}
              hostPort: {{ .Values.clcpysynxxljobexecutor.networkManager.thrift.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 7895
              hostPort: 7895
              protocol: TCP
        {{- end }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
            {{- if .Values.clcpysynxxljobexecutor.networkManager.tomcat.port }}
              port: {{ .Values.clcpysynxxljobexecutor.networkManager.tomcat.port }}
            {{- else }}
              port: 15236
            {{- end }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10
        {{- if .Values.clcpysynxxljobexecutor.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clcpysynxxljobexecutor.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clcpysynxxljobexecutor.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clcpysynxxljobexecutor.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clcpysynxxljobexecutor.resourceManager.resources.requests.memory }}
        {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 128Mi
        {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
            - mountPath: /home/nacfg.ini
              name: nacfg
              subPath: nacfg.ini
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env2: user
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
    {{- if .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            name: base-config
          name: base
    {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            name: base-config
          name: base
    {{- end }}
