apiVersion: v1
kind: Service
metadata:
  name: clopenapidataservice
  namespace: user
spec:
  ports:
    - name: thrift
      port: 12338
      protocol: TCP
      targetPort: 12338
  selector:
    app: clopenapidataservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}