apiVersion: v1
kind: Service
metadata:
  name: clopenapi-nodeport
  namespace: user
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 31013
      port: 13338
      protocol: TCP
      targetPort: 13338
    - name: thrift
      nodePort: 31023
      port: 11003
      protocol: TCP
      targetPort: 11003
  selector:
    app: clopenapi
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}