apiVersion: v1
kind: Service
metadata:
  name: clthirdssoweb
  namespace: user
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 30111
      port: 12360
      protocol: TCP
      targetPort: 12360
  selector:
    app: clthirdssoweb
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
