apiVersion: v1
kind: Service
metadata:
  name: unifieduserjavadataservice
  namespace: user
spec:
  ports:
    - name: thrift
      port: 13758
      protocol: TCP
      targetPort: 13758
  selector:
    app: unifieduserjavadataservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}