apiVersion: apps/v1
kind: Deployment
metadata:
  name: clapproveintegrateservice
  namespace: budget
spec:
  progressDeadlineSeconds: 600
{{- if .Values.clapproveintegrateservice.nodeManager.replicas }}
  replicas: {{ .Values.clapproveintegrateservice.nodeManager.replicas }}
{{- else if eq .Values.environment "test" }}
  replicas: 1
{{- else if eq .Values.environment "formal" }}
  replicas: 2
{{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clapproveintegrateservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        armsPilotAutoEnable: 'on'
        armsPilotCreateAppName: clapproveintegrateservice
        redeploy-timestamp: '1598022814952'
      labels:
        app: clapproveintegrateservice
    spec:
      containers:
        - env:
            - name: MYENV_CONFIGNAME
              value: >-
                dbroute,jdbc,logconfig,paramjdbc,serviceroute,application,rabbitmq,redis
            - name: MYENV_CONFIGPROFILE
              value: zs
            - name: MYENV_CONFIGLABEL
              value: CLApproveIntegrateService
            - name: MYENV_CONFIGSERVICEID
              value: spring-cloud-config-server
            - name: MYENV_EUREKAURL
              value: >-
                http://eureka1:8000/eureka/,http://eureka2:8000/eureka/,http://eureka3:8000/eureka/
            - name: MYENV_TOMCATPORT
              {{- if .Values.clapproveintegrateservice.networkManager.tomcat.port }}
              value: {{ .Values.clapproveintegrateservice.networkManager.tomcat.port | quote }}
              {{- else }}
              value: "10299"
              {{- end }}
            - name: JAVA_OPTS
              value: >-
                {{ .Values.clapproveintegrateservice.resourceManager.jvm }}
          {{- if .Values.clapproveintegrateservice.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clapproveintegrateservice:{{ .Values.clapproveintegrateservice.nodeManager.tag }}
          {{- else }}
          image: {{ .Values.imageRegistry }}/clapproveintegrateservice:{{ .Values.dockerTag }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                {{- if .Values.clapproveintegrateservice.networkManager.command.url }}
                command:
                  - curl
                  - {{ .Values.clapproveintegrateservice.networkManager.command.url }}
                {{- else }}
                command:
                  - curl
                  - 'http://localhost:10299/unregisterbyext'
                {{- end }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
              {{- if .Values.clapproveintegrateservice.networkManager.tomcat.port }}
              port: {{ .Values.clapproveintegrateservice.networkManager.tomcat.port }}
              {{- else }}
              port: 10299
              {{- end }}
              scheme: HTTP
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: clapproveintegrateservice
          ports:
            {{- if .Values.clapproveintegrateservice.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clapproveintegrateservice.networkManager.tomcat.port }}
              hostPort: {{ .Values.clapproveintegrateservice.networkManager.tomcat.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 10299
              hostPort: 10299
              protocol: TCP
            {{- end }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
              {{- if .Values.clapproveintegrateservice.networkManager.tomcat.port }}
              port: {{ .Values.clapproveintegrateservice.networkManager.tomcat.port }}
              {{- else }}
              port: 10299
              {{- end }}
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10
          {{- if .Values.clapproveintegrateservice.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clapproveintegrateservice.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clapproveintegrateservice.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clapproveintegrateservice.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clapproveintegrateservice.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 128Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/nacfg.ini
              name: base
              subPath: nacfg.ini
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
    {{- if .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            name: base-config
          name: base
    {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            name: base-config
          name: base
    {{- end }}
