apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clapproveh5
  name: clapproveh5
  namespace: budget
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clapproveh5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clapproveh5
    spec:
      containers:
        - env:
            - name: MYENV_TOMCATPORT
              {{- if .Values.clapproveh5.networkManager.tomcat.port }}
              value: {{ .Values.clapproveh5.networkManager.tomcat.port | quote }}
              {{- else }}
              value: '14965'
              {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.clapproveh5.resourceManager.jvm }}
          {{- if .Values.clapproveh5.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clapproveh5:{{ .Values.clapproveh5.nodeManager.tag }}
          {{- else }}
          image: {{ .Values.imageRegistry }}/clapproveh5:{{ .Values.dockerTag }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          name: clapproveh5
          ports:
              {{- if .Values.clapproveh5.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clapproveh5.networkManager.tomcat.port }}
              hostPort: {{ .Values.clapproveh5.networkManager.tomcat.port }}
              protocol: TCP
              {{- else }}
            - containerPort: 14965
              hostPort: 14965
              protocol: TCP
              {{- end }}
          {{- if .Values.clapproveh5.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clapproveh5.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clapproveh5.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clapproveh5.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clapproveh5.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 128Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
            - mountPath: /home/nacfg.ini
              name: nacfg
            - mountPath: /usr/local/soft/tomcat/webapps/ROOT/WEB-INF/config
              name: config
            - mountPath: /usr/local/soft/tomcat/conf/server.xml
              name: config
              subPath: server.xml
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env: budget
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
      {{- if .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
        - configMap:
            defaultMode: 420
            items:
              - key: server.xml
                path: server.xml
            name: clapproveh5-config
          name: config
      {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
        - configMap:
            defaultMode: 420
            items:
              - key: server.xml
                path: server.xml
            name: clapproveh5-config
          name: config
      {{- end }}
