apiVersion: apps/v1
kind: Deployment
metadata:
  name: clapprovalbussservice
  namespace: budget
spec:
  progressDeadlineSeconds: 600
{{- if .Values.clapprovalbussservice.nodeManager.replicas }}
  replicas: {{ .Values.clapprovalbussservice.nodeManager.replicas }}
{{- else if eq .Values.environment "test" }}
  replicas: 1
{{- else if eq .Values.environment "formal" }}
  replicas: 2
{{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clapprovalbussservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clapprovalbussservice
    spec:
      containers:
        - env:
            - name: MYENV_CONFIGNAME
              value: dbroute,jdbc,logconfig,paramjdbc,serviceroute,application,log4j,systemparam,javamonitorgathercomponet
            - name: MYENV_CONFIGPROFILE
              value: zs
            - name: MYENV_CONFIGLABEL
              value: CLApprovalBussService
            - name: MYENV_CONFIGSERVICEID
              value: spring-cloud-config-server
            - name: MYENV_EUREKAURL
              value: http://eureka1:8000/eureka/,http://eureka2:8000/eureka/,http://eureka3:8000/eureka/
            - name: MYENV_TOMCATPORT
            {{- if .Values.clapprovalbussservice.networkManager.tomcat.port }}
              value: {{ .Values.clapprovalbussservice.networkManager.tomcat.port | quote }}
            {{- else }}
              value: "17100"
            {{- end }}
            - name: JAVA_OPTS
              value: >-
                {{ .Values.clapprovalbussservice.resourceManager.jvm }}
        {{- if .Values.clapprovalbussservice.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clapprovalbussservice:{{ .Values.clapprovalbussservice.nodeManager.tag }}
        {{- else }}
          image: {{ .Values.imageRegistry }}/clapprovalbussservice:{{ .Values.dockerTag }}
        {{- end }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                {{- if .Values.clapprovalbussservice.networkManager.command.url }}
                command:
                  - curl
                  - {{ .Values.clapprovalbussservice.networkManager.command.url }}
                {{- else }}
                command:
                  - curl
                  - 'http://localhost:17100/unregisterbyext'
                {{- end }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
            {{- if .Values.clapprovalbussservice.networkManager.tomcat.port }}
              port: {{ .Values.clapprovalbussservice.networkManager.tomcat.port }}
            {{- else }}
              port: 17100
            {{- end }}
              scheme: HTTP
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: clapprovalbussservice
          ports:
          {{- if .Values.clapprovalbussservice.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clapprovalbussservice.networkManager.tomcat.port }}
              hostPort: {{ .Values.clapprovalbussservice.networkManager.tomcat.port }}
              protocol: TCP
          {{- else }}
            - containerPort: 17100
              hostPort: 17100
              protocol: TCP
          {{- end }}
          {{- if .Values.clapprovalbussservice.networkManager.thrift.port }}
            - containerPort: {{ .Values.clapprovalbussservice.networkManager.thrift.port }}
              hostPort: {{ .Values.clapprovalbussservice.networkManager.thrift.port }}
              protocol: TCP
          {{- else }}
            - containerPort: 17102
              hostPort: 17102
              protocol: TCP
          {{- end }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
            {{- if .Values.clapprovalbussservice.networkManager.tomcat.port }}
              port: {{ .Values.clapprovalbussservice.networkManager.tomcat.port }}
            {{- else }}
              port: 17100
            {{- end }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10
        {{- if .Values.clapprovalbussservice.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clapprovalbussservice.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clapprovalbussservice.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clapprovalbussservice.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clapprovalbussservice.resourceManager.resources.requests.memory }}
        {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 128Mi
        {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/nacfg.ini
              name: base
              subPath: nacfg.ini
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
    {{- if .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            name: base-config
          name: base
    {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            name: base-config
          name: base
    {{- end }}
