apiVersion: v1
kind: Service
metadata:
  name: clapproveh5-nodeport
  namespace: budget
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: clapproveh5
      nodePort: 30780
      port: 14965
      protocol: TCP
      targetPort: 14965
  selector:
    app: clapproveh5
  sessionAffinity: None
  type: NodePort

