apiVersion: apps/v1
kind: Deployment
metadata:
  name: clexpensecontroldataservice
  namespace: budget
spec:
  progressDeadlineSeconds: 600
  {{- if .Values.clexpensecontroldataservice.nodeManager.replicas }}
  replicas: {{ .Values.clexpensecontroldataservice.nodeManager.replicas }}
  {{- else if eq .Values.environment "test" }}
  replicas: 1
  {{- else if eq .Values.environment "formal" }}
  replicas: 2
  {{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clexpensecontroldataservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clexpensecontroldataservice
    spec:
      containers:
        - env:
            - name: MYENV_CONFIGNAME
              value: 'application,dbroute,logconfig,serviceroute'
            - name: MYENV_CONFIGPROFILE
              value: zs
            - name: MYENV_CONFIGLABEL
              value: CLExpenseControlDataService
            - name: MYENV_CONFIGSERVICEID
              value: spring-cloud-config-server
            - name: MYENV_EUREKAURL
              value: >-
                http://eureka1:8000/eureka/,http://eureka2:8000/eureka/,http://eureka3:8000/eureka/
            - name: MYENV_TOMCATPORT
              {{- if .Values.clexpensecontroldataservice.networkManager.tomcat.port }}
              value: {{ .Values.clexpensecontroldataservice.networkManager.tomcat.port | quote }}
              {{- else }}
              value: "7727"
              {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.clexpensecontroldataservice.resourceManager.jvm }}
          {{- if .Values.clexpensecontroldataservice.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clexpensecontroldataservice:{{ .Values.clexpensecontroldataservice.nodeManager.tag }}
          {{- else }}
          image: {{ .Values.imageRegistry }}/clexpensecontroldataservice:{{ .Values.dockerTag }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                {{- if .Values.clexpensecontroldataservice.networkManager.command.url }}
                command:
                  - curl
                  - {{ .Values.clexpensecontroldataservice.networkManager.command.url }}
                {{- else }}
                command:
                  - curl
                  - 'http://localhost:7727/unregisterbyext'
                {{- end }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
              {{- if .Values.clexpensecontroldataservice.networkManager.tomcat.port }}
              port: {{ .Values.clexpensecontroldataservice.networkManager.tomcat.port }}
              {{- else }}
              port: 7727
              {{- end }}
              scheme: HTTP
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: clexpensecontroldataservice
          ports:
            {{- if .Values.clexpensecontroldataservice.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clexpensecontroldataservice.networkManager.tomcat.port }}
              hostPort: {{ .Values.clexpensecontroldataservice.networkManager.tomcat.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 7727
              hostPort: 7727
              protocol: TCP
            {{- end }}
            {{- if .Values.clexpensecontroldataservice.networkManager.thrift.port }}
            - containerPort: {{ .Values.clexpensecontroldataservice.networkManager.thrift.port }}
              hostPort: {{ .Values.clexpensecontroldataservice.networkManager.thrift.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 12365
              hostPort: 12365
              protocol: TCP
            {{- end }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
              {{- if .Values.clexpensecontroldataservice.networkManager.tomcat.port }}
              port: {{ .Values.clexpensecontroldataservice.networkManager.tomcat.port }}
              {{- else }}
              port: 7727
              {{- end }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10
          {{- if .Values.clexpensecontroldataservice.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clexpensecontroldataservice.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clexpensecontroldataservice.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clexpensecontroldataservice.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clexpensecontroldataservice.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 128Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/nacfg.ini
              name: base
              subPath: nacfg.ini
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env3: budget
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
      {{- if .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            name: base-config
          name: base
      {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            name: base-config
          name: base
      {{- end }}
