apiVersion: v1
kind: Service
metadata:
  name: clsmsservice
  namespace: budget
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 31794
      port: 12370
      targetPort: 12370
      protocol: TCP
  selector:
    app: clsmsservice
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
