apiVersion: v1
kind: Service
metadata:
  name: clstandardsettingdbservice-svc
  namespace: budget
spec:
  ports:
    - name: thrift
      {{- if .Values.clstandardsettingdbservice.networkManager.thrift.port }}
      port: {{ .Values.clstandardsettingdbservice.networkManager.thrift.port }}
      protocol: TCP
      targetPort: {{ .Values.clstandardsettingdbservice.networkManager.thrift.port }}
      {{- else }}
      protocol: TCP
      port: 12962
      targetPort: 12962
      {{- end }}
  selector:
    app: clstandardsettingdbservice
  sessionAffinity: None
  type: ClusterIP
