apiVersion: v1
kind: Service
metadata:
  name: clusercareweb-nodeport
  namespace: budget
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: clusercareweb
      nodePort: 30720
      port: 13097
      protocol: TCP
      targetPort: 13097
  selector:
    app: clusercareweb
  sessionAffinity: None
  type: NodePort
