apiVersion: apps/v1
kind: Deployment
metadata:
  name: clconspdetailcreatepro
  namespace: settlement
spec:
  progressDeadlineSeconds: 600
{{- if .Values.clconspdetailcreatepro.nodeManager.replicas }}
  replicas: {{ .Values.clconspdetailcreatepro.nodeManager.replicas }}
{{- else if eq .Values.environment "test" }}
  replicas: 1
{{- else if eq .Values.environment "formal" }}
  replicas: 2
{{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clconspdetailcreatepro
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        redeploy-timestamp: '1599785304723'
      labels:
        app: clconspdetailcreatepro
    spec:
      containers:
        - env:
            - name: MYENV_CONFIGNAME
              value: >-
                dbroute,jdbc,logconfig,paramjdbc,redis,serviceroute,application,businessConfig
            - name: MYENV_CONFIGPROFILE
              value: zs
            - name: MYENV_CONFIGLABEL
              value: CLConspDetailCreatePro-PEK-ZS-k8s
            - name: MYENV_CONFIGSERVICEID
              value: spring-cloud-config-server
            - name: MYENV_EUREKAURL
              value: >-
                http://eureka1:8000/eureka/,http://eureka2:8000/eureka/,http://eureka3:8000/eureka/
            - name: MYENV_TOMCATPORT
            {{- if .Values.clconspdetailcreatepro.networkManager.tomcat.port }}
              value: {{ .Values.clconspdetailcreatepro.networkManager.tomcat.port | quote }}
            {{- else }}
              value: '13221'
            {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.clconspdetailcreatepro.resourceManager.jvm }}
        {{- if .Values.clconspdetailcreatepro.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clconspdetailcreatepro:{{ .Values.clconspdetailcreatepro.nodeManager.tag }}
        {{- else }}
          image: {{ .Values.imageRegistry }}/clconspdetailcreatepro:{{ .Values.dockerTag }}
        {{- end }}
          imagePullPolicy: IfNotPresent
          name: clconspdetailcreatepro
          ports:
          {{- if .Values.clconspdetailcreatepro.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clconspdetailcreatepro.networkManager.tomcat.port }}
              hostPort: {{ .Values.clconspdetailcreatepro.networkManager.tomcat.port }}
              protocol: TCP
          {{- else }}
            - containerPort: 13221
              hostPort: 13221
              protocol: TCP
          {{- end }}
          {{- if .Values.clconspdetailcreatepro.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clconspdetailcreatepro.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clconspdetailcreatepro.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clconspdetailcreatepro.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clconspdetailcreatepro.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
            - mountPath: /home/nacfg.ini
              name: nacfg
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env: settlement
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
      {{- if .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
      {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
      {{- end }}
