apiVersion: v1
kind: Service
metadata:
  name: clconspdetaildataservice
  namespace: settlement
spec:
  ports:
    - name: thrift
      port: 12298
      protocol: TCP
      targetPort: 12298
  selector:
    app: clconspdetaildataservice
  sessionAffinity: None
  type: ClusterIP
