apiVersion: apps/v1
kind: Deployment
metadata:
  name: clreportservice
  namespace: settlement
spec:
  progressDeadlineSeconds: 600
{{- if .Values.clreportservice.nodeManager.replicas }}
  replicas: {{ .Values.clreportservice.nodeManager.replicas }}
{{- else if eq .Values.environment "test" }}
  replicas: 1
{{- else if eq .Values.environment "formal" }}
  replicas: 2
{{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clreportservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        redeploy-timestamp: '1598021843332'
      labels:
        app: clreportservice
    spec:
      containers:
        - env:
            - name: MYENV_CONFIGNAME
              value: >-
                dbroute,jdbc,logconfig,paramjdbc,serviceroute,redis,mqhelper,application,javaMonitorGatherComponet,log4j
            - name: MYENV_CONFIGPROFILE
              value: zs
            - name: MYENV_CONFIGLABEL
              value: cLReportService-PEK -k8s-ZS
            - name: MYENV_CONFIGSERVICEID
              value: spring-cloud-config-server
            - name: MYENV_EUREKAURL
              value: >-
                http://eureka1:8000/eureka/,http://eureka2:8000/eureka/,http://eureka3:8000/eureka/
            - name: MYENV_TOMCATPORT
            {{- if .Values.clreportservice.networkManager.tomcat.port }}
              value: {{ .Values.clreportservice.networkManager.tomcat.port | quote }}
            {{- else }}
              value: '9191'
            {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.clreportservice.resourceManager.jvm }}
          {{- if .Values.clreportservice.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clreportservice:{{ .Values.clreportservice.nodeManager.tag }}
          {{- else }}
          image: {{ .Values.imageRegistry }}/clreportservice:{{ .Values.dockerTag }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
            {{- if .Values.clreportservice.networkManager.tomcat.port }}
              port: {{ .Values.clreportservice.networkManager.tomcat.port }}
            {{- else }}
              port: 9191
            {{- end }}
            timeoutSeconds: 1
          name: clreportservice
          ports:
          {{- if .Values.clreportservice.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clreportservice.networkManager.tomcat.port }}
              hostPort: {{ .Values.clreportservice.networkManager.tomcat.port }}
              protocol: TCP
          {{- else }}
            - containerPort: 9191
              hostPort: 9191
              protocol: TCP
          {{- end }}
          {{- if .Values.clreportservice.networkManager.thrift.port }}
            - containerPort: {{ .Values.clreportservice.networkManager.thrift.port }}
              hostPort: {{ .Values.clreportservice.networkManager.thrift.port }}
              protocol: TCP
          {{- else }}
            - containerPort: 9193
              hostPort: 9193
              protocol: TCP
          {{- end }}
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
            {{- if .Values.clreportservice.networkManager.tomcat.port }}
              port: {{ .Values.clreportservice.networkManager.tomcat.port }}
            {{- else }}
              port: 9191
            {{- end }}
            timeoutSeconds: 1
          {{- if .Values.clreportservice.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clreportservice.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clreportservice.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clreportservice.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clreportservice.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '2'
              memory: 2868Mi
            requests:
              cpu: 200m
              memory: 256Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
            - mountPath: /home/nacfg.ini
              name: nacfg
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env: settlement
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
      {{- if .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
      {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
      {{- end }}
