apiVersion: apps/v1
kind: Deployment
metadata:
  name: clreportdataservice
  namespace: settlement
spec:
  progressDeadlineSeconds: 600
{{- if .Values.clreportdataservice.nodeManager.replicas }}
  replicas: {{ .Values.clreportdataservice.nodeManager.replicas }}
{{- else if eq .Values.environment "test" }}
  replicas: 1
{{- else if eq .Values.environment "formal" }}
  replicas: 2
{{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clreportdataservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clreportdataservice
    spec:
      containers:
        - env:
            - name: MYENV_CONFIGNAME
              value: >-
                dbroute,jdbc,logconfig,paramjdbc,serviceroute,application,javaMonitorGatherComponet,log4j
            - name: MYENV_CONFIGPROFILE
              value: zs
            - name: MYENV_CONFIGLABEL
              value: CLReportDataService-PAL2-k8s-ZS
            - name: MYENV_CONFIGSERVICEID
              value: spring-cloud-config-server
            - name: MYENV_EUREKAURL
              value: >-
                http://eureka1:8000/eureka/,http://eureka2:8000/eureka/,http://eureka3:8000/eureka/
            - name: MYENV_TOMCATPORT
            {{- if .Values.clreportdataservice.networkManager.tomcat.port }}
              value: {{ .Values.clreportdataservice.networkManager.tomcat.port | quote }}
            {{- else }}
              value: '12403'
            {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.clreportdataservice.resourceManager.jvm }}
          {{- if .Values.clreportdataservice.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clreportdataservice:{{ .Values.clreportdataservice.nodeManager.tag }}
          {{- else }}
          image: {{ .Values.imageRegistry }}/clreportdataservice:{{ .Values.dockerTag }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          name: clreportdataservice
          ports:
            {{- if .Values.clreportdataservice.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clreportdataservice.networkManager.tomcat.port }}
              hostPort: {{ .Values.clreportdataservice.networkManager.tomcat.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 12403
              hostPort: 12403
              protocol: TCP
            {{- end }}
            {{- if .Values.clreportdataservice.networkManager.thrift.port }}
            - containerPort: {{ .Values.clreportdataservice.networkManager.thrift.port }}
              hostPort: {{ .Values.clreportdataservice.networkManager.thrift.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 14412
              hostPort: 14412
              protocol: TCP
            {{- end }}
          {{- if .Values.clreportdataservice.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clreportdataservice.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clreportdataservice.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clreportdataservice.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clreportdataservice.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 128Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
            - mountPath: /home/nacfg.ini
              name: nacfg
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env: settlement
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
      {{- if .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
      {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
      {{- end }}
