apiVersion: apps/v1
kind: Deployment
metadata:
  name: clsettlementjobexecutor
  namespace: settlement
spec:
  progressDeadlineSeconds: 600
  {{- if .Values.clsettlementjobexecutor.nodeManager.replicas }}
  replicas: {{ .Values.clsettlementjobexecutor.nodeManager.replicas }}
  {{- else if eq .Values.environment "test" }}
  replicas: 1
  {{- else if eq .Values.environment "formal" }}
  replicas: 2
  {{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clsettlementjobexecutor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clsettlementjobexecutor
    spec:
      containers:
        - env:
            - name: MYENV_CONFIGNAME
              value: >-
                dbroute,jdbc,logconfig,paramjdbc,serviceroute,redis,mqhelper,application,javaMonitorGatherComponet,log4j
            - name: MYENV_CONFIGPROFILE
              value: zs
            - name: MYENV_CONFIGLABEL
              value: CLSettlementJobExecutor-PAL-K8S-ZS
            - name: MYENV_CONFIGSERVICEID
              value: spring-cloud-config-server
            - name: MYENV_EUREKAURL
              value: >-
                http://eureka1:8000/eureka/,http://eureka2:8000/eureka/,http://eureka3:8000/eureka/
            - name: MYENV_TOMCATPORT
            {{- if .Values.clsettlementjobexecutor.networkManager.tomcat.port }}
              value: {{ .Values.clsettlementjobexecutor.networkManager.tomcat.port | quote }}
            {{- else }}
              value: '12964'
            {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.clsettlementjobexecutor.resourceManager.jvm }}
          {{- if .Values.clsettlementjobexecutor.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clsettlementjobexecutor:{{ .Values.clsettlementjobexecutor.nodeManager.tag }}
          {{- else }}
          image: {{ .Values.imageRegistry }}/clsettlementjobexecutor:{{ .Values.dockerTag }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              {{- if .Values.clsettlementjobexecutor.networkManager.command.url }}
              command:
                - curl
                - {{ .Values.clsettlementjobexecutor.networkManager.command.url }}
              {{- else }}
              command:
                - curl
                - 'localhost:12964/info'
              {{- end }}
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: clsettlementjobexecutor
          ports:
            {{- if .Values.clsettlementjobexecutor.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clsettlementjobexecutor.networkManager.tomcat.port }}
              hostPort: {{ .Values.clsettlementjobexecutor.networkManager.tomcat.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 12964
              hostPort: 12964
              protocol: TCP
            {{- end }}
            {{- if .Values.clsettlementjobexecutor.networkManager.thrift.port }}
            - containerPort: {{ .Values.clsettlementjobexecutor.networkManager.thrift.port }}
              hostPort: {{ .Values.clsettlementjobexecutor.networkManager.thrift.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 9001
              hostPort: 9001
              protocol: TCP
            {{- end }}
          {{- if .Values.clsettlementjobexecutor.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clsettlementjobexecutor.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clsettlementjobexecutor.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clsettlementjobexecutor.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clsettlementjobexecutor.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 128Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
            - mountPath: /home/nacfg.ini
              name: nacfg
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env: settlement
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
      {{- if .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
      {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
      {{- end }}
