apiVersion: v1
kind: Service
metadata:
  name: clbusscarh5-nodeport
  namespace: car
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30080
      port: 13766
      protocol: TCP
      targetPort: 13766
  selector:
    app: clbusscarh5
  sessionAffinity: None
  type: NodePort
