apiVersion: v1
kind: Service
metadata:
  name: cltransportuserservice
  namespace: car
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 31895
      port: 6834
      protocol: TCP
      targetPort: 6834
  selector:
    app: cltransportuserservice
  sessionAffinity: None
  type: NodePort
