apiVersion: v1
kind: Service
metadata:
  name: cltransportorderservice
  namespace: car
spec:
  ports:
    - name: http
      port: 12272
      protocol: TCP
      targetPort: 12272
  selector:
    app: cltransportorderservice
  sessionAffinity: None
  type: ClusterIP
