apiVersion: v1
kind: Service
metadata:
  name: cltransporttradeintegration
  namespace: car
spec:
  ports:
    - name: http
      port: 13004
      protocol: TCP
      targetPort: 13004
  selector:
    app: cltransporttradeintegration
  sessionAffinity: None
  type: ClusterIP
