apiVersion: apps/v1
kind: Deployment
metadata:
  name: clbussuserweb
  namespace: common
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clbussuserweb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        redeploy-timestamp: '1598966297651'
      labels:
        app: clbussuserweb
    spec:
      containers:
        - env:
            - name: MYENV_TOMCATPORT
              {{- if not .Values.clbussuserweb.networkManager.tomcat.port }}
              value: {{ .Values.clbussuserweb.networkManager.tomcat.port | quote }}
              {{- else }}
              value: "12130"
              {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.clbussuserweb.resourceManager.jvm }}
          {{- if .Values.clbussuserweb.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clbussuserweb:{{ .Values.clbussuserweb.nodeManager.tag }}
          {{- else }}
          image: {{ .Values.imageRegistry }}/clbussuserweb:{{ .Values.dockerTag }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /Content/img/active.png
              {{- if not .Values.clbussuserweb.networkManager.tomcat.port }}
              port: {{ .Values.clbussuserweb.networkManager.tomcat.port }}
              {{- else }}
              port: 12130
              {{- end }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: clbussuserweb
          ports:
            {{- if not .Values.clbussuserweb.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clbussuserweb.networkManager.tomcat.port }}
              hostPort: {{ .Values.clbussuserweb.networkManager.tomcat.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 12130
              hostPort: 12130
              protocol: TCP
            {{- end }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /Content/img/active.png
              {{- if not .Values.clbussuserweb.networkManager.tomcat.port }}
              port: {{ .Values.clbussuserweb.networkManager.tomcat.port }}
              {{- else }}
              port: 12130
              {{- end }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10
          {{- if .Values.clbussuserweb.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clbussuserweb.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clbussuserweb.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clbussuserweb.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clbussuserweb.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 1200Mi
            requests:
              cpu: 100m
              memory: 128Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
            - mountPath: /home/nacfg.ini
              name: nacfg
            - mountPath: /usr/local/soft/tomcat/webapps/ROOT/WEB-INF/config
              name: config
            - mountPath: /usr/local/soft/tomcat/conf/catalina.properties
              name: config
              subPath: catalina.properties
            - mountPath: /usr/local/soft/tomcat/conf/server.xml
              name: config
              subPath: server.xml
            - mountPath: >-
                /usr/local/soft/tomcat/webapps/ROOT/Content/i18n/strings_www_517la_com.properties
              name: config
              subPath: strings_www_517la_com.properties
            - mountPath: >-
                /usr/local/soft/tomcat/webapps/ROOT/Content/i18n/strings_wcslo.properties
              name: config
              subPath: strings_wcslo.properties
            - mountPath: >-
                /usr/local/soft/tomcat/webapps/ROOT/WEB-INF/classes/com/better517na/cLBussUserWeb/config/app-content.xml
              name: config
              subPath: app-content.xml
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env: common
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
      {{- if not .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            name: clbussuserweb-config
          name: config
      {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            name: clbussuserweb-config
          name: config
      {{- end }}
