apiVersion: v1
kind: Service
metadata:
  name: clbusstmcweb-nodeport
  namespace: common
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 30000
      port: 12170
      protocol: TCP
      targetPort: 12170
  selector:
    app: clbusstmcweb
  sessionAffinity: None
  type: NodePort
