apiVersion: v1
kind: Service
metadata:
  name: clbussuserweb-nodeport
  namespace: common
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 30002
      port: 12130
      protocol: TCP
      targetPort: 12130
  selector:
    app: clbussuserweb
  sessionAffinity: None
  type: NodePort
