apiVersion: apps/v1
kind: Deployment
metadata:
  name: clrequestauthorizationservice
  namespace: common
spec:
  progressDeadlineSeconds: 600
  {{- if not .Values.clrequestauthorizationservice.nodeManager.replicas }}
  replicas: {{ .Values.clrequestauthorizationservice.nodeManager.replicas }}
  {{- else if eq .Values.environment "test" }}
  replicas: 1
  {{- else if eq .Values.antiAffinity "formal" }}
  replicas: 2
  {{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clrequestauthorizationservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        redeploy-timestamp: '1602663067771'
      labels:
        app: clrequestauthorizationservice
    spec:
      containers:
        - env:
            - name: MYENV_CONFIGNAME
              value: 'application,dbroute,logconfig'
            - name: MYENV_CONFIGPROFILE
              value: zs
            - name: MYENV_CONFIGLABEL
              value: CLRequestAuthorizationService-PALCS
            - name: MYENV_CONFIGSERVICEID
              value: spring-cloud-config-server
            - name: MYENV_EUREKAURL
              value: >-
                http://eureka1:8000/eureka/,http://eureka2:8000/eureka/,http://eureka3:8000/eureka/
            - name: MYENV_TOMCATPORT
              {{- if not .Values.clrequestauthorizationservice.networkManager.tomcat.port }}
              value: {{ .Values.clrequestauthorizationservice.networkManager.tomcat.port | quote }}
              {{- else }}
              value: "13940"
              {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.clrequestauthorizationservice.resourceManager.jvm }}
          {{- if .Values.clrequestauthorizationservice.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clrequestauthorizationservice:{{ .Values.clrequestauthorizationservice.nodeManager.tag }}
          {{- else }}
          image: {{ .Values.imageRegistry }}/clrequestauthorizationservice:{{ .Values.dockerTag }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                {{- if not .Values.clrequestauthorizationservice.networkManager.command.url }}
                command:
                  - curl
                  - {{ .Values.clrequestauthorizationservice.networkManager.command.url }}
                {{- else }}
                command:
                  - curl
                  - 'http://localhost:13940/unregisterbyext'
                {{- end }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
              {{- if not .Values.clrequestauthorizationservice.networkManager.tomcat.port }}
              port: {{ .Values.clrequestauthorizationservice.networkManager.tomcat.port }}
              {{- else }}
              port: 13940
              {{- end }}
              scheme: HTTP
            initialDelaySeconds: 1000
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: clrequestauthorizationservice
          ports:
            {{- if not .Values.clrequestauthorizationservice.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clrequestauthorizationservice.networkManager.tomcat.port }}
              hostPort: {{ .Values.clrequestauthorizationservice.networkManager.tomcat.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 13940
              hostPort: 13940
              protocol: TCP
            {{- end }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
              {{- if not .Values.clrequestauthorizationservice.networkManager.tomcat.port }}
              port: {{ .Values.clrequestauthorizationservice.networkManager.tomcat.port }}
              {{- else }}
              port: 13940
              {{- end }}
              scheme: HTTP
            initialDelaySeconds: 1000
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10
          {{- if .Values.clrequestauthorizationservice.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clrequestauthorizationservice.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clrequestauthorizationservice.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clrequestauthorizationservice.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clrequestauthorizationservice.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
            - mountPath: /home/nacfg.ini
              name: nacfg
            - mountPath: /usr/local/soft/nacfgpek.ini
              name: nacfgpek
              subPath: nacfgpek.ini
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env2: common
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
      {{- if not .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            items:
              - key: nacfgpek.ini
                path: nacfgpek.ini
            name: clrequestauthorizationservice-configmap
          name: nacfgpek
      {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            items:
              - key: nacfgpek.ini
                path: nacfgpek.ini
            name: clrequestauthorizationservice-configmap
          name: nacfgpek
      {{- end }}
