apiVersion: v1
kind: Service
metadata:
  name: clrequestauthorizationservice-svc
  namespace: common
spec:
  ports:
    - name: http
      port: 13940
      protocol: TCP
      targetPort: 13940
  selector:
    app: clrequestauthorizationservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}