apiVersion: v1
kind: Service
metadata:
  name: cltrainpaynotifywebsite-nodeport
  namespace: train
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31304
      port: 9294
      protocol: TCP
      targetPort: 9294
  selector:
    app: cltrainpaynotifywebsite
  sessionAffinity: None
  type: NodePort
