apiVersion: v1
kind: Service
metadata:
  name: cltraintradeintegrateservice-svc
  namespace: train
spec:
  ports:
    - port: 12438
      protocol: TCP
      targetPort: 12438
  selector:
    app: cltraintradeintegrateservice
  sessionAffinity: None
  type: ClusterIP

