apiVersion: v1
kind: Service
metadata:
  name: cltrainticketwebspa-nodeport
  namespace: train
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30084
      port: 13494
      protocol: TCP
      targetPort: 13494
  selector:
    app: cltrainticketwebspa
  sessionAffinity: None
  type: NodePort

