apiVersion: v1
kind: Service
metadata:
  name: cltrainticketsnotifywebsite-nodeport
  namespace: train
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32550
      port: 9288
      protocol: TCP
      targetPort: 9288
  selector:
    app: cltrainticketsnotifywebsite
  sessionAffinity: None
  type: NodePort
