apiVersion: v1
kind: Service
metadata:
  name: clairticketplatmanageweb-svc
  namespace: jp
spec:
  clusterIP: 172.26.10.221
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 30010
      port: {{ .Values.clairticketplatmanageweb.service.thriftport }}
      protocol: TCP
      targetPort: {{ .Values.clairticketplatmanageweb.service.thriftport }}
  selector:
    app: clairticketplatmanageweb
  sessionAffinity: None
  type: NodePort

