apiVersion: v1
kind: Service
metadata:
  name: clairticketproductqueryservice-svc
  namespace: jp
spec:
  ports:
    - name: http
      port: {{ .Values.aggregationpayservice.service.port }}
      protocol: TCP
      targetPort: {{ .Values.aggregationpayservice.service.port }}
  selector:
    app: clairticketproductqueryservice
  sessionAffinity: None
  type: ClusterIP

