apiVersion: v1
kind: Service
metadata:
  name: clairticketnotifytaskconsumer
  namespace: jp
spec:
  ports:
    - name: http
      port: {{ .Values.clairticketnotifytaskconsumer.service.port }}
      protocol: TCP
      targetPort: {{ .Values.clairticketnotifytaskconsumer.service.port }}
  selector:
    app: clairticketnotifytaskconsumer
  sessionAffinity: None
  type: ClusterIP

