apiVersion: apps/v1
kind: Deployment
metadata:
  name: clairpurchasinginterface
  namespace: jp
spec:
  progressDeadlineSeconds: 600
{{- if .Values.clairpurchasinginterface.nodeManager.replicas }}
  replicas: {{ .Values.clairpurchasinginterface.nodeManager.replicas }}
{{- else if eq .Values.environment "test" }}
  replicas: 1
{{- else if eq .Values.environment "formal" }}
  replicas: 2
{{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clairpurchasinginterface
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clairpurchasinginterface
    spec:
      containers:
        - env:
            - name: MYENV_CONFIGNAME
              value: >-
                application,dbroute,logconfig,serviceroute
            - name: MYENV_CONFIGPROFILE
              value: zs
            - name: MYENV_CONFIGLABEL
              value: CLAirPurchasingInterface-PAL-K8S-ZS
            - name: MYENV_CONFIGSERVICEID
              value: spring-cloud-config-server
            - name: MYENV_EUREKAURL
              value: >-
                http://eureka1:8000/eureka/,http://eureka2:8000/eureka/,http://eureka3:8000/eureka/
            - name: MYENV_TOMCATPORT
            {{- if .Values.clairpurchasinginterface.networkManager.tomcat.port }}
              value: {{ .Values.clairpurchasinginterface.networkManager.tomcat.port | quote }}
            {{- else }}
              value: "12367"
            {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.clairpurchasinginterface.resourceManager.jvm }}
        {{- if .Values.clairpurchasinginterface.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clairpurchasinginterface:{{ .Values.clairpurchasinginterface.nodeManager.tag }}
        {{- else }}
          image: {{ .Values.imageRegistry }}/clairpurchasinginterface:{{ .Values.dockerTag }}
        {{- end }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                {{- if .Values.clairpurchasinginterface.networkManager.command.url }}
                command:
                  - curl
                  {{ .Values.clairpurchasinginterface.networkManager.command.url }}
                {{- else }}
                command:
                  - curl
                  - 'http://localhost:12367/unregisterbyext'
                {{- end }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
            {{- if .Values.clairpurchasinginterface.networkManager.tomcat.port }}
              port: {{ .Values.clairpurchasinginterface.networkManager.tomcat.port }}
            {{- else }}
              port: 12367
            {{- end }}
              scheme: HTTP
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: clairpurchasinginterface
          ports:
            {{- if .Values.clairpurchasinginterface.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clairpurchasinginterface.networkManager.tomcat.port }}
              hostPort: {{ .Values.clairpurchasinginterface.networkManager.tomcat.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 12367
              hostPort: 12367
              protocol: TCP
            {{- end }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
            {{- if .Values.clairpurchasinginterface.networkManager.tomcat.port }}
              port: {{ .Values.clairpurchasinginterface.networkManager.tomcat.port }}
            {{- else }}
              port: 12367
            {{- end }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10
          {{- if .Values.clairpurchasinginterface.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clairpurchasinginterface.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clairpurchasinginterface.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clairpurchasinginterface.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clairpurchasinginterface.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 1600Mi
            requests:
              cpu: 500m
              memory: 800Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/local/soft/travelsky.cer
              name: config
              subPath: travelsky.cer
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
            - mountPath: /home/nacfg.ini
              name: nacfg
            - mountPath: /srv/access/WTG000000003.pfx
              name: wtg000000003
            - mountPath: /srv/access/GNETEWEB.cer
              name: gneteweb
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env: jp
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
    {{- if .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            items:
              - key: travelsky.cer
                path: travelsky.cer
            name: clairpurchasinginterface-config
          name: config
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
        - hostPath:
            path: /srv/access/GNETEWEB.cer
            type: ''
          name: gneteweb
        - hostPath:
            path: /srv/access/WTG000000003.pfx
            type: ''
          name: wtg000000003
    {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - configMap:
            defaultMode: 420
            items:
              - key: travelsky.cer
                path: travelsky.cer
            name: clairpurchasinginterface-config
          name: config
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
        - hostPath:
            path: /srv/access/GNETEWEB.cer
            type: ''
          name: gneteweb
        - hostPath:
            path: /srv/access/WTG000000003.pfx
            type: ''
          name: wtg000000003
    {{- end }}
