apiVersion: v1
kind: Service
metadata:
  name: clairticketbuytradeintegration-svc
  namespace: jp
spec:
  ports:
    - name: http
      port: {{ .Values.clairticketbuytradeintegration.service.port }}
      protocol: TCP
      targetPort: {{ .Values.clairticketbuytradeintegration.service.port }}
  selector:
    app: clairticketbuytradeintegration
  sessionAffinity: None
  type: ClusterIP

