apiVersion: v1
kind: Service
metadata:
  name: clbussairticketh52-nodeport
  namespace: jp
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      nodePort: 30005
      port: {{ .Values.clbussairticketh52.service.port }}
      protocol: TCP
      targetPort: {{ .Values.clbussairticketh52.service.port }}
  selector:
    app: clbussairticketh52
  sessionAffinity: None
  type: NodePort

