apiVersion: v1
kind: Service
metadata:
  name: clconfiguredataservice
  namespace: common
spec:
  ports:
    - name: thrift
      port: {{ .Values.clconfiguredataservice.service.thriftport }}
      protocol: TCP
      targetPort: {{ .Values.clconfiguredataservice.service.thriftport }}
  selector:
    app: clconfiguredataservice
  sessionAffinity: None
  type: ClusterIP

