apiVersion: v1
kind: Service
metadata:
  name: clformvalidatedataservice
  namespace: jp
spec:
  ports:
    - name: thrift
      port: {{ .Values.clformvalidatedataservice.service.thriftport }}
      protocol: TCP
      targetPort: {{ .Values.clformvalidatedataservice.service.thriftport }}
  selector:
    app: clformvalidatedataservice
  sessionAffinity: None
  type: ClusterIP

