apiVersion: v1
kind: Service
metadata:
  name: clorderoperlogservice
  namespace: jp
spec:
  ports:
    - name: http
      port: {{ .Values.clorderoperlogservice.service.port }}
      protocol: TCP
      targetPort: {{ .Values.clorderoperlogservice.service.port }}
  selector:
    app: clorderoperlogservice
  sessionAffinity: None
  type: ClusterIP
