apiVersion: apps/v1
kind: Deployment
metadata:
  name: clproductcenterservice
  namespace: jp
spec:
  progressDeadlineSeconds: 600
{{- if .Values.clproductcenterservice.nodeManager.replicas }}
  replicas: {{ .Values.clproductcenterservice.nodeManager.replicas }}
{{- else if eq .Values.environment "test" }}
  replicas: 1
{{- else if eq .Values.environment "formal" }}
  replicas: 2
{{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: clproductcenterservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: clproductcenterservice
    spec:
      containers:
        - env:
            - name: MYENV_CONFIGNAME
              value: >-
                application,dbroute,logconfig,serviceroute
            - name: MYENV_CONFIGPROFILE
              value: zs
            - name: MYENV_CONFIGLABEL
              value: clproductcenterservice-PAL-K8S-ZS
            - name: MYENV_CONFIGSERVICEID
              value: spring-cloud-config-server
            - name: MYENV_EUREKAURL
              value: >-
                http://eureka1:8000/eureka/,http://eureka2:8000/eureka/,http://eureka3:8000/eureka/
            - name: MYENV_TOMCATPORT
            {{- if .Values.clproductcenterservice.networkManager.tomcat.port }}
              value: {{ .Values.clproductcenterservice.networkManager.tomcat.port | quote }}
            {{- else }}
              value: "13890"
            {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.clproductcenterservice.resourceManager.jvm }}
        {{- if .Values.clproductcenterservice.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/clproductcenterservice:{{ .Values.clproductcenterservice.nodeManager.tag }}
        {{- else }}
          image: {{ .Values.imageRegistry }}/clproductcenterservice:{{ .Values.dockerTag }}
        {{- end }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                {{- if .Values.clproductcenterservice.networkManager.command.url }}
                command:
                  - curl
                  - {{ .Values.clproductcenterservice.networkManager.command.url }}
                {{- else }}
                command:
                  - curl
                  - 'http://localhost:13890/unregisterbyext'
                {{- end }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
            {{- if .Values.clproductcenterservice.networkManager.tomcat.port }}
              port: {{ .Values.clproductcenterservice.networkManager.tomcat.port }}
            {{- else }}
              port: 13890
            {{- end }}
              scheme: HTTP
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: clproductcenterservice
          ports:
            {{- if .Values.clproductcenterservice.networkManager.tomcat.port }}
            - containerPort: {{ .Values.clproductcenterservice.networkManager.tomcat.port }}
              hostPort: {{ .Values.clproductcenterservice.networkManager.tomcat.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 13890
              hostPort: 13890
              protocol: TCP
            {{- end }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
            {{- if .Values.clproductcenterservice.networkManager.tomcat.port }}
              port: {{ .Values.clproductcenterservice.networkManager.tomcat.port }}
            {{- else }}
              port: 13890
            {{- end }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 10
          {{- if .Values.clproductcenterservice.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.clproductcenterservice.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.clproductcenterservice.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.clproductcenterservice.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.clproductcenterservice.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/nacfg.ini
              name: nacfg
              subPath: nacfg.ini
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env: jp
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
    {{- if .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
    {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
    {{- end }}
