apiVersion: v1
kind: Service
metadata:
  name: clrefundticketbusiservice-svc
  namespace: jp
spec:
  ports:
    - name: http
      port: {{ .Values.clrefundticketbusiservice.service.port }}
      protocol: TCP
      targetPort: {{ .Values.clrefundticketbusiservice.service.port }}
  selector:
    app: clrefundticketbusiservice
  sessionAffinity: None
  type: ClusterIP

