apiVersion: v1
kind: Service
metadata:
  name: clticketchangeservice-svc
  namespace: jp
spec:
  ports:
    - name: http
      port: {{ .Values.clticketchangeservice.service.port }}
      protocol: TCP
      targetPort: {{ .Values.clticketchangeservice.service.port }}
  selector:
    app: clticketchangeservice
  sessionAffinity: None
  type: ClusterIP
