apiVersion: apps/v1
kind: Deployment
metadata:
  name: jbusinessbasedataservice
  namespace: jp
spec:
  progressDeadlineSeconds: 600
{{- if .Values.jbusinessbasedataservice.nodeManager.replicas }}
  replicas: {{ .Values.jbusinessbasedataservice.nodeManager.replicas }}
{{- else if eq .Values.environment "test" }}
  replicas: 1
{{- else if eq .Values.environment "formal" }}
  replicas: 2
{{- end }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jbusinessbasedataservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jbusinessbasedataservice
    spec:
      containers:
        - env:
            - name: MYENV_TOMCATPORT
            {{- if .Values.jbusinessbasedataservice.networkManager.tomcat.port }}
              value: {{ .Values.jbusinessbasedataservice.networkManager.tomcat.port | quote }}
            {{- else }}
              value: "8170"
            {{- end }}
            - name: JAVA_OPTS
              value: {{ .Values.jbusinessbasedataservice.resourceManager.jvm }}
        {{- if .Values.jbusinessbasedataservice.nodeManager.tag }}
          image: {{ .Values.imageRegistry }}/jbusinessbasedataservice:{{ .Values.jbusinessbasedataservice.nodeManager.tag }}
        {{- else }}
          image: {{ .Values.imageRegistry }}/jbusinessbasedataservice:{{ .Values.dockerTag }}
        {{- end }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 100
            periodSeconds: 10
            successThreshold: 1
            {{- if .Values.jbusinessbasedataservice.networkManager.tomcat.port }}
            tcpSocket:
              port: {{ .Values.jbusinessbasedataservice.networkManager.tomcat.port }}
            {{- else }}
            tcpSocket:
              port: 8170
            {{- end }}
            timeoutSeconds: 10
          name: jbusinessbasedataservice
          ports:
            {{- if .Values.jbusinessbasedataservice.networkManager.tomcat.port }}
            - containerPort: {{ .Values.jbusinessbasedataservice.networkManager.tomcat.port }}
              hostPort: {{ .Values.jbusinessbasedataservice.networkManager.tomcat.port }}
              protocol: TCP
            {{- else }}
            - containerPort: 8170
              hostPort: 8170
              protocol: TCP
            {{- end }}
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            {{- if .Values.jbusinessbasedataservice.networkManager.tomcat.port }}
            tcpSocket:
              port: {{ .Values.jbusinessbasedataservice.networkManager.tomcat.port }}
            {{- else }}
            tcpSocket:
              port: 8170
            {{- end }}
            timeoutSeconds: 10
          {{- if .Values.jbusinessbasedataservice.resourceManager.resources.custom -}}
          resources:
            limits:
              cpu: {{ .Values.jbusinessbasedataservice.resourceManager.resources.limits.cpu }}
              memory: {{ .Values.jbusinessbasedataservice.resourceManager.resources.limits.memory }}
            requests:
              cpu: {{ .Values.jbusinessbasedataservice.resourceManager.resources.requests.cpu }}
              memory: {{ .Values.jbusinessbasedataservice.resourceManager.resources.requests.memory }}
          {{- else }}
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          {{- end }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/nacfg.ini
              name: nacfg
              subPath: nacfg.ini
            - mountPath: /var/log/cllog
              name: cllog
            - mountPath: /var/log/java
              name: logjava
            - mountPath: /usr/local/soft/tomcat/webapps/ROOT/WEB-INF/config
              name: config
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        env: jp
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 15
    {{- if .Values.hostManager.volumes.hostPath }}
      volumes:
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: {{ .Values.hostManager.volumes.hostPath }}/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
        - configMap:
            defaultMode: 420
            name: jbusinessbasedataservice-config
          name: config
    {{- else }}
      volumes:
        - hostPath:
            path: /app/log/cllog
            type: ''
          name: cllog
        - hostPath:
            path: /app/log/java
            type: ''
          name: logjava
        - hostPath:
            path: /home/nacfg.ini
            type: ''
          name: nacfg
        - configMap:
            defaultMode: 420
            name: jbusinessbasedataservice-config
          name: config
    {{- end }}
