apiVersion: v1
kind: Service
metadata:
  name: ticketsaletradeintegration-svc
  namespace: jp
spec:
  ports:
    - name: http
      port: {{ .Values.ticketsaletradeintegration.service.port }}
      protocol: TCP
      targetPort: {{ .Values.ticketsaletradeintegration.service.port }}
  selector:
    app: ticketsaletradeintegration
  sessionAffinity: None
  type: ClusterIP

