# The base hadoop image to use for all components.
# See this repo for image build details: https://github.com/Comcast/kube-yarn/tree/master/image
imageRegistry:

dockerTag: 1.0.0

environment: "formal"

hostManager:
  volumes:
    hostPath: /app

configMapManger:
  db:
    serviceroute:
      url: jdbc:mysql://ServiceRouteDB-R.BJ01.517na.com/ServiceRouteDB
      username: JmllLBwCJN7P5a0VXvvHkg@@
      password: 6BPzhGiVwAPCW1LhtdUvCblGokvcMGesrY1wV/coEWg@
    writeroute:
      url: jdbc:mysql://DataBaseRoute-R.BJ01.517na.com:3306/DataBaseRoute
      username: JmllLBwCJN7P5a0VXvvHkg@@
      password: 6BPzhGiVwAPCW1LhtdUvCblGokvcMGesrY1wV/coEWg@
    readroute:
      url: jdbc:mysql://DataBaseRoute-R.BJ01.517na.com:3306/DataBaseRoute
      username: JmllLBwCJN7P5a0VXvvHkg@@
      password: 6BPzhGiVwAPCW1LhtdUvCblGokvcMGesrY1wV/coEWg@
  redis:
    url: jdbc:mysql://DataBaseRoute-W.BJ01.517na.com:3306/DataBaseRoute
    username: kSRw85/S628Jd6cTkHmEgA@@
    password: 6BPzhGiVwAPCW1LhtdUvCblGokvcMGesrY1wV/coEWg@
    dbname: CLTradeRedisDB
  xxjob:
    db:
      url: jdbc:mysql://rm-2zer4gx7otl4s391e.mysql.rds.aliyuncs.com:3306/xxl-job?useUnicode=true&characterEncoding=UTF-8
      username: xxljob
      password: Aa123@321Bb
    email:
      host: smtp.163.com
      port: 25
      username: yangxilong@517na.com
      password: asdfzxcv
      sendNick: 《任务调度平台XXL-JOB》
    login:
      username: admin
      password: 123456
    ldap:
      host: 172.17.3.28
      port: 389
      domain: 517na.com


clapprovalbussservice:
  networkManager:
    tomcat:
      port: 17100
    thrift:
      port: 17102
    command:
      url: 'http://localhost:17100/unregisterbyext'
  resourceManager:
    resources:
      custom: false
      requests:
        memory: 128Mi
        cpu: 200m
      limits:
        memory: 1Gi
        cpu: '1'
    jvm: '-server -Xms128m -Xmx1024m'
  nodeManager:
    tag: 1.0.0
#    replicas: 2
  service:
    clusterIP:


clapprovaldataservice:
  networkManager:
    tomcat:
      port:
    thrift:
      port:
    command:
      url:
  resourceManager:
    resources:
      custom: false
      requests:
        memory:
        cpu:
      limits:
        memory:
        cpu:
    jvm: >-
      -server -Xms128m -Xmx1g
      -javaagent:/usr/local/soft/skywalking/agent65/skywalking-agent.jar
      -DSW_AGENT_COLLECTOR_BACKEND_SERVICES=10.10.80.240:31101
      -DSW_AGENT_NAME=CLApprovalDataService -DSW_LOGGING_LEVEL=ERROR
  nodeManager:
    tag: 1.0.0


clapproveintegrateservice:
  networkManager:
    tomcat:
      port:
    thrift:
      port:
    command:
      url:
  resourceManager:
    resources:
      custom: false
      requests:
        memory:
        cpu:
      limits:
        memory:
        cpu:
    jvm: -server -Xms512m -Xmx2560m
  nodeManager:
    tag: 1.0.0


clexpensecontroldataservice:
  networkManager:
    tomcat:
      port:
    thrift:
      port:
    command:
      url:
  resourceManager:
    resources:
      custom: false
      requests:
        memory:
        cpu:
      limits:
        memory:
        cpu:
    jvm: '-server -Xms128m -Xmx1g'
  nodeManager:
    tag: 1.0.0


clexpensecontrolservice:
  networkManager:
    tomcat:
      port:
    thrift:
      port:
    command:
      url:
  resourceManager:
    resources:
      custom: false
      requests:
        memory:
        cpu:
      limits:
        memory:
        cpu:
    jvm: -server -Xms128m -Xmx1g
      -javaagent:/usr/local/soft/skywalking/agent65/skywalking-agent.jar
      -DSW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalkingadmin:31101
      -DSW_AGENT_NAME=clexpensecontrolservice -DSW_LOGGING_LEVEL=ERROR
  nodeManager:
    tag: 1.0.0


clfilemanageservice:
  networkManager:
    tomcat:
      port: 8053
      name: 8053tcp80530
    thrift:
      port: 8153
      name: 8153tcp81530
    command:
      url: 'http://localhost:8053/unregisterbyext'
  resourceManager:
    resources:
      custom: false
      requests:
        memory:
        cpu:
      limits:
        memory:
        cpu:
    jvm: '-server -Xms128m -Xmx1024m'
  nodeManager:
    tag: 1.0.0


clsmsservice:
  networkManager:
    tomcat:
      port:
    thrift:
      port:
    command:
      url:
  resourceManager:
    resources:
      custom: false
      requests:
        memory:
        cpu:
      limits:
        memory:
        cpu:
    jvm: -server -Xms128m -Xmx512m
  nodeManager:
    tag: 1.0.0
  service:
    nodePort: 30602



clstandardbusinessservice:
  networkManager:
    tomcat:
      port:
    thrift:
      port:
    command:
      url:
  resourceManager:
    resources:
      custom: false
      requests:
        memory:
        cpu:
      limits:
        memory:
        cpu:
    jvm: '-server -Xms128m -Xmx1024m'
  nodeManager:
    tag: 1.0.0


clstandardintegrateservice:
  networkManager:
    tomcat:
      port:
    thrift:
      port:
    command:
      url:
  resourceManager:
    resources:
      custom: false
      requests:
        memory:
        cpu:
      limits:
        memory:
        cpu:
    jvm: -server -Xms128m -Xmx1024m -XX:PermSize=128m
      -XX:MaxPermSize=256m
      -javaagent:/usr/local/soft/skywalking/agent65/skywalking-agent.jar
      -DSW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalkingadmin:31101
      -DSW_AGENT_NAME=clstandardintegrateservice
      -DSW_LOGGING_LEVEL=ERROR
  nodeManager:
    tag: 1.0.0


clstandardsettingdbservice:
  networkManager:
    tomcat:
      port:
    thrift:
      port:
    command:
      url:
  resourceManager:
    resources:
      custom: false
      requests:
        memory:
        cpu:
      limits:
        memory:
        cpu:
    jvm: -server -Xms128m -Xmx1024m
      -javaagent:/usr/local/soft/skywalking/agent65/skywalking-agent.jar
      -DSW_AGENT_COLLECTOR_BACKEND_SERVICES=10.10.80.240:31101
      -DSW_AGENT_NAME=clstandardsettingdbservice
      -DSW_LOGGING_LEVEL=ERROR
  nodeManager:
    tag: 1.0.0



clusercareintegrateservice:
  networkManager:
    tomcat:
      port:
    thrift:
      port:
    command:
      url:
  resourceManager:
    resources:
      custom: false
      requests:
        memory:
        cpu:
      limits:
        memory:
        cpu:
    jvm: -server -Xms128m -Xmx512m
      -javaagent:/usr/local/soft/skywalking/agent65/skywalking-agent.jar
      -DSW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalkingadmin:31101
      -DSW_AGENT_NAME=clopenapi -DSW_LOGGING_LEVEL=ERROR
  nodeManager:
    tag: 1.0.0

clapproveh5:
  networkManager:
    tomcat:
      port:
    thrift:
      port:
    command:
      url:
  resourceManager:
    resources:
      custom: false
      requests:
        memory:
        cpu:
      limits:
        memory:
        cpu:
    jvm: '-server -Xms128m -Xmx512m'
  nodeManager:
    tag: 1.0.0

clusercareweb:
  networkManager:
    tomcat:
      port: 13097
  resourceManager:
    resources:
      custom: false
      requests:
        memory:
        cpu:
      limits:
        memory:
        cpu:
    jvm: '-server -Xms128m -Xmx512m'
  nodeManager:
    tag: 1.0.0
